name: "Job Setup"
description: "Checkout code, install Python & uv"
runs:
  using: composite
  steps:
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
